import React from "react";
import Head from "next/head";
const PageMataTag = () => {
  return (
    <>
      <Head>
        <title>Exclusive Games</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link aria-label="favicon" rel="icon" href="/favicon.ico" />
        <meta name="title" content="Exclusive Games. Pasión por ganar" />
        <meta
          name="description"
          content="Elevate your success with our Proxies"
        />
        {/* <!-- Open Graph / Facebook --> */}
        <meta property="og:type" content="website" />
        <meta
          property="og:url"
          content="https://my-app-eta-weld.vercel.app/"
        />
        <meta
          property="og:title"
          content="Exclusive Games. Pasión por ganar
"
        />
        <meta
          property="og:description"
          content="Exclusive Games. Pasión por ganar
"
        />
        <meta
          property="og:image"
          content="https://my-app-eta-weld.vercel.app/MetaTag.png"
        />
        {/* <!-- Twitter --> */}
        <meta
          property="twitter:card"
          content="Elevate your success with our Proxies"
        />
        <meta
          property="twitter:url"
          content="https://my-app-eta-weld.vercel.app/"
        />
        <meta
          property="twitter:title"
          content="Exclusive Games. Pasión por ganar
"
        />
        <meta
          property="twitter:description"
          content="Exclusive Games. Pasión por ganar
"
        />
        <meta
          property="twitter:image"
          content="https://my-app-eta-weld.vercel.app/MetaTag.png"
        />
      </Head>
    </>
  );
};

export default PageMataTag;
